name = "atlas-sub"
main = "src/index.js"
compatibility_date = "2023-08-01"

kv_namespaces = [
  { binding = "SUBSCRIPTIONS", id = "SUBSCRIPTIONS_ID", preview_id = "SUBSCRIPTIONS_PREVIEW_ID" }
]

[vars]
ADMIN_TOKEN = "admin_token_change_me"
VISITOR_TOKEN = "visitor_token_change_me"
SUB_CONVERT_API = "https://api.v1.mk/sub" 