name = "atlas-sub"
main = "src/index.js"
compatibility_date = "2023-08-01"

# KV命名空间配置
# 如果未配置，系统将使用内存KV作为备用
# 创建KV命名空间：npx wrangler kv:namespace create SUBSCRIPTIONS
# 创建预览KV命名空间：npx wrangler kv:namespace create SUBSCRIPTIONS --preview
kv_namespaces = [
  { binding = "SUBSCRIPTIONS", id = "", preview_id = "" }
]

[vars]
ADMIN_TOKEN = "admin_token_change_me"
VISITOR_TOKEN = "visitor_token_change_me"
SUB_CONVERT_API = "https://api.v1.mk/sub"

# 静态资源配置
[site]
bucket = "./public"
